version: "3.8"
services:

  app:
    ports:
      - "${APP_PORT-3000}:${APP_PORT-3000}"
    command: bash -c "ls -al && /bin/bash run.sh"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/.venv
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
  